name: 01 - Building Blocks

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello, Word - created by JN!"  
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Successful step
              run: |
                echo "I will success - created by JN!"  
                exit 0
            - name: Say goodbye
              run: |
                echo "Goodbye - created by JN!" 
