name: 03 - Workflow Runners

on: 
    push:

jobs:
    echo-on-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                echo "This job is running on an Ubuntu runner - created by JN!"
                echo "Runner OS: [ $RUNNER_OS ] - created by JN!"